export const types = {
  FETCH_CART_ITEMS_REQUEST: 'FETCH_CART_ITEMS',
  FETCH_CART_ITEMS_SUCCESS: 'FETCH_CART_SUCCESS',
  FETCH_CART_ITEMS_FAILURE: 'FETCH_CART_FAILURE',
  POST_ITEM_TO_CART_REQUEST: 'POST_ITEM_TO_CART_REQUEST',
  POST_ITEM_TO_CART_SUCCESS: ' POST_ITEM_TO_CART_SUCCESS',
  POST_ITEM_TO_CART_FAILURE: 'POST_ITEM_TO_CART_FAILURE',
  DELETE_ITEM_FROM_CART_REQUEST: 'DELETE_ITEM_FROM_CART_REQUEST',
  DELETE_ITEM_FROM_CART_SUCCESS: 'DELETE_ITEM_FROM_CART_SUCCESS',
  DELETE_ITEM_FROM_CART_FAILURE: 'DELETE_ITEM_FROM_CART_FAILURE',
  CLEAR_CART_ITEMS_REQUEST: 'CLEAR_CART_ITEMS_REQUEST',
  CLEAR_CART_ITEMS_SUCCESS: 'CLEAR_CART_ITEMS_SUCCESS',
  CLEAR_CART_ITEMS_FAILURE: 'CLEAR_CART_ITEMS_FAILURE',
};
