export const types = {
  SIGN_IN_USER_REQUEST: 'SIGN_IN_USER_REQUEST',
  SIGN_IN_USER_REQUEST_SUCCESS: 'SIGN_IN_USER_REQUEST_SUCCESS',
  SIGN_IN_USER_REQUEST_FAILURE: 'SIGN_IN_USER_REQUEST_FAILURE',
  SIGN_UP_USER_REQUEST: 'SIGN_UP_USER_REQUEST',
  SIGN_UP_USER_REQUEST_SUCCESS: 'SIGN_UP_USER_REQUEST_SUCCESS',
  SIGN_UP_USER_REQUEST_FAILURE: 'SIGN_UP_USER_REQUEST_FAILURE',
  SIGN_OUT_USER_REQUEST: 'SIGN_OUT_USER_REQUEST',
  SIGN_OUT_USER_REQUEST_SUCCESS: 'SIGN_OUT_USER_REQUEST_SUCCESS',
  SIGN_OUT_USER_REQUEST_FAILURE: 'SIGN_OUT_USER_REQUEST_FAILURE',
};
